### ISSUE TITLE
Extension not upgraded for healthier v3?

### ISSUE THREAD

**Issue by NathanielHill** [KidkArolis/vscode-healthier#5]
```
[Info  - 11:05:38 AM] Healthier server is running.
[Info  - 11:05:39 AM] Healthier library loaded from: /home/nhill/Code/ariadne/node_modules/healthier/index.js
[Error - 11:05:39 AM] Healthier stack trace:
[Error - 11:05:39 AM] Error: Failed to load config "standard" to extend from.
Referenced from: BaseConfig
    at configMissingError (/home/nhill/Code/ariadne/node_modules/eslint/lib/cli-engine/config-array-factory.js:233:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/home/nhill/Code/ariadne/node_modules/eslint/lib/cli-engine/config-array-factory.js:708:23)
    at ConfigArrayFactory._loadExtends (/home/nhill/Code/ariadne/node_modules/eslint/lib/cli-engine/config-array-factory.js:613:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/home/nhill/Code/ariadne/node_modules/eslint/lib/cli-engine/config-array-factory.js:545:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/home/nhill/Code/ariadne/node_modules/eslint/lib/cli-engine/config-array-factory.js:491:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at createConfigArray (/home/nhill/Code/ariadne/node_modules/eslint/lib/cli-engine/config-array-factory.js:307:25)
    at ConfigArrayFactory.create (/home/nhill/Code/ariadne/node_modules/eslint/lib/cli-engine/config-array-factory.js:362:16)
    at createBaseConfigArray (/home/nhill/Code/ariadne/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:84:48)
```

**Comment by NathanielHill** [comment]
This comes after upgrading `healthier` from v2 to v3.

The `healthier` cli still works, the extension no longer does

**Comment by NathanielHill** [comment]
@KidkArolis

**Comment by victordidenko** [comment]
@KidkArolis any new here? Just stumbled upon this...

**Comment by KidkArolis** [comment]
Oops - missed this (using Sublime Text myself..). Let's see if #6 PR fixed it.

**Comment by KidkArolis** [comment]
Seems to be working now with 3.0.0 version of extension!

![image](https://user-images.githubusercontent.com/324440/66480274-32d00b80-ea96-11e9-85f9-861f78dbf2fc.png)

Huge thanks to @victordidenko / @yumauri and sorry for the delay everyone :(
